# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: blog
description: "Blog de Thierry Chappuis"
keywords: "web, python, django, flask"
url: http://thierry.chappuis.net
baseurl: "/blog"

google_analytics: 
repo: http://github.com/tchappui/blog
disqus_shortname: "thierrychappuisnet"
disqus_site_shortname: "thierrychappuisnet"

# Author settings
author:
  name: Thierry Chappuis
  job: Data scientist & back-end engineer
  bio: "Ingénieur passionné par le développement web, la data science et la programmation scientifique."
  thumb: /images/author.jpg
  email: tchappui@gmail.com
  url: http://thierry.chappuis.net/
  github: https://github.com/tchappui
  twitter: https://twitter.com/tchappui
  facebook: https://facebook.com/tchappui
  linkedin: https://linkedin.com/in/tchappui

# navbar pages
navbar:
  - slug: about
    title: Qui suis-je?
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
